CREATE TABLE players(
    Player VARCHAR NOT NULL
    ID int NOT NULL
    PRIMARY KEY (Player, ID)
);

CREATE TABLE 2016_17_nbaavgs (
	ID int NOT NULL,
    Player VARCHAR NOT NULL,
    G int,
    GS int,
    MP int,
    FG int,
    FGA int,
    3P int,
    3PA int,
    3P% int,
    2P int,
    2PA int,
    2P% int,
    eFG% int,
    FT int,
    FTA int,
    FT% int,
    ORB int,
    DRB int,
    TRB int,
    AST int,
    STL int,
    BLK int,
    TOV int,
    PF int,
    PTS int,
    PER int,
    BPM int,
    VOPR int,
    FOREIGN KEY (ID) REFERENCES players (ID)
    FOREIGN KEY (Player) REFERENCES players (Player),
    PRIMARY KEY (ID, Player)
);

CREATE TABLE 2017_18_nbaavgs(
    ID int NOT NULL,
    Player VARCHAR NOT NULL,
    G int,
    GS int,
    MP int,
    FG int,
    FGA int,
    3P int,
    3PA int,
    3P% int,
    2P int,
    2PA int,
    2P% int,
    eFG% int,
    FT int,
    FTA int,
    FT% int,
    ORB int,
    DRB int,
    TRB int,
    AST int,
    STL int,
    BLK int,
    TOV int,
    PF int,
    PTS int,
    PER int,
    BPM int,
    VOPR int,
    FOREIGN KEY (ID) REFERENCES players (ID),
    FOREIGN KEY (Player) REFERENCES players (Player),
    PRIMARY KEY (ID,Player)

);
CREATE TABLE 2018_19_nbaavgs(
    ID int NOT NULL,
    Player VARCHAR NOT NULL,
    G int,
    GS int,
    MP int,
    FG int,
    FGA int,
    3P int,
    3PA int,
    3P% int,
    2P int,
    2PA int,
    2P% int,
    eFG% int,
    FT int,
    FTA int,
    FT% int,
    ORB int,
    DRB int,
    TRB int,
    AST int,
    STL int,
    BLK int,
    TOV int,
    PF int,
    PTS int,
    PER int,
    BPM int,
    VOPR int,
    FOREIGN KEY (ID) REFERENCES players(ID),
    FOREIGN KEY (Player) REFERENCES players(Player),
    PRIMARY KEY (ID,Player)
);

CREATE TABLE 2019_20_nbaavgs(
    ID int NOT NULL,
    Player VARCHAR NOT NULL,
    G int,
    GS int,
    MP int,
    FG int,
    FGA int,
    3P int,
    3PA int,
    3P% int,
    2P int,
    2PA int,
    2P% int,
    eFG% int,
    FT int,
    FTA int,
    FT% int,
    ORB int,
    DRB int,
    TRB int,
    AST int,
    STL int,
    BLK int,
    TOV int,
    PF int,
    PTS int,
    PER int,
    BPM int,
    VOPR int,
    FOREIGN KEY (ID) REFERENCES players (ID),
    FOREIGN KEY (Player) REFERENCES players (Player),
    PRIMARY KEY (ID,Player)
);   
    
CREATE TABLE 2020_21_nbaavgs(
    ID int NOT NULL,
    Player VARCHAR NOT NULL,
    G int,
    GS int,
    MP int,
    FG int,
    FGA int,
    3P int,
    3PA int,
    3P% int,
    2P int,
    2PA int,
    2P% int,
    eFG% int,
    FT int,
    FTA int,
    FT% int,
    ORB int,
    DRB int,
    TRB int,
    AST int,
    STL int,
    BLK int,
    TOV int,
    PF int,
    PTS int,
    PER int,
    BPM int,
    VOPR int,
    FOREIGN KEY (ID) REFERENCES players (ID),
    FOREIGN KEY (Player) REFERENCES players (Player),
    PRIMARY KEY (ID,Player)
);