CREATE TABLE players(
    Player VARCHAR NOT NULL,
    player_id int NOT NULL,
    PRIMARY KEY (Player, player_id),
	UNIQUE (Player,player_id)
);
CREATE TABLE nbaavgs_2016_17 (
	player_id int NOT NULL,
    Player VARCHAR NOT NULL,
    G int,
    GS int,
    MP int,
    FG int,
    FGA int,
    three_point_made int,
    three_point_attempt int,
    three_point_percent int,
    two_point_made int,
    two_point_attempt int,
    two_point_percent int,
    eFG_percent int,
    FT int,
    FTA int,
    FT_percent int,
    ORB int,
    DRB int,
    TRB int,
    AST int,
    STL int,
    BLK int,
    TOV int,
    PF int,
    PTS int,
    PER int,
    BPM int,
    VOPR int,
    FOREIGN KEY (Player,player_id) REFERENCES players (Player,player_id),
    PRIMARY KEY (player_id, Player)
);

CREATE TABLE nbaavgs_2017_18 (
 	player_id int NOT NULL,
    Player VARCHAR NOT NULL,
    G int,
    GS int,
    MP int,
    FG int,
    FGA int,
    three_point_made int,
    three_point_attempt int,
    three_point_percent int,
    two_point_made int,
    two_point_attempt int,
    two_point_percent int,
    eFG_percent int,
    FT int,
    FTA int,
    FT_percent int,
    ORB int,
    DRB int,
    TRB int,
    AST int,
    STL int,
    BLK int,
    TOV int,
    PF int,
    PTS int,
    PER int,
    BPM int,
    VOPR int,
    FOREIGN KEY (Player,player_id) REFERENCES players (Player,player_id),
    PRIMARY KEY (player_id, Player)
);
CREATE TABLE nbaavgs_2018_19 (
	player_id int NOT NULL,
    Player VARCHAR NOT NULL,
    G int,
    GS int,
    MP int,
    FG int,
    FGA int,
    three_point_made int,
    three_point_attempt int,
    three_point_percent int,
    two_point_made int,
    two_point_attempt int,
    two_point_percent int,
    eFG_percent int,
    FT int,
    FTA int,
    FT_percent int,
    ORB int,
    DRB int,
    TRB int,
    AST int,
    STL int,
    BLK int,
    TOV int,
    PF int,
    PTS int,
    PER int,
    BPM int,
    VOPR int,
    FOREIGN KEY (Player,player_id) REFERENCES players (Player,player_id),
    PRIMARY KEY (player_id, Player)
);

CREATE TABLE nbaavgs_2019_20 (
	player_id int NOT NULL,
    Player VARCHAR NOT NULL,
    G int,
    GS int,
    MP int,
    FG int,
    FGA int,
    three_point_made int,
    three_point_attempt int,
    three_point_percent int,
    two_point_made int,
    two_point_attempt int,
    two_point_percent int,
    eFG_percent int,
    FT int,
    FTA int,
    FT_percent int,
    ORB int,
    DRB int,
    TRB int,
    AST int,
    STL int,
    BLK int,
    TOV int,
    PF int,
    PTS int,
    PER int,
    BPM int,
    VOPR int,
    FOREIGN KEY (Player,player_id) REFERENCES players (Player,player_id),
    PRIMARY KEY (player_id, Player)
);   
    
CREATE TABLE nbaavgs_2020_21 (
	player_id int NOT NULL,
    Player VARCHAR NOT NULL,
    G int,
    GS int,
    MP int,
    FG int,
    FGA int,
    three_point_made int,
    three_point_attempt int,
    three_point_percent int,
    two_point_made int,
    two_point_attempt int,
    two_point_percent int,
    eFG_percent int,
    FT int,
    FTA int,
    FT_percent int,
    ORB int,
    DRB int,
    TRB int,
    AST int,
    STL int,
    BLK int,
    TOV int,
    PF int,
    PTS int,
    PER int,
    BPM int,
    VOPR int,
    FOREIGN KEY (Player,player_id) REFERENCES players (Player,player_id),
    PRIMARY KEY (player_id, Player)
);