CREATE TABLE main (
        id int NOT NULL,
        u_player VARCHAR NOT NULL,
        player VARCHAR NOT NULL,
        year int,
        g int,
        gs int,
        mp int,
        fg int,
        fga int,
        threepoint int,
        threepoint_att int,
        threepoint_perc float,
        twopoint int,
        twopoint_att int,
        twopoint_perc float,
        efg_perc float,
        PRIMARY KEY (id, u_player),
        UNIQUE (id, u_player);

CREATE TABLE misc (
        id int NOT NULL,
        u_player VARCHAR NOT NULL,
        player VARCHAR NOT NULL,
        year int,
        ft int,
        fta int,
        ft_perc float,
        ora int,
        drb int,
        trb int,
        ast int,
        stl int,
        blk int,
        tov int,
        pf int,
        pts int,
        per int,
        bpm int,
        vorp int;)